/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bittle.beansmod;

import java.io.IOException;
import java.nio.file.*;
import static java.nio.file.StandardCopyOption.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.concurrent.TimeUnit;
import javax.swing.JFileChooser;
import static org.bittle.beansmod.Connection.response;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.Exceptions;
import org.openide.util.NbPreferences;
import org.openide.windows.WindowManager;

final class BittlePanel extends javax.swing.JPanel {

    private final BittleOptionsPanelController controller;
    private final BittleTreeTopComponent fileTree; 
    private final Connection connection;
    private final String serverName = "wss://notextures.io:8086";
    private final SyncList syncList;
    
    private String username = "";
    private String password = "";
    private String rootpath = System.getProperty("user.home") + "\\Bittle";
    private boolean loggedIn = false;

    BittlePanel(BittleOptionsPanelController controller, Connection connection) {
        this.controller = controller;
        this.connection = connection;
        this.fileTree = (BittleTreeTopComponent) WindowManager.getDefault().findTopComponent("BittleTree");
        this.syncList = SyncList.getInstance();
        
        store();
        initComponents();
        
        LogInPanel.setVisible(true);
        LoggedInPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionsLayeredPane = new javax.swing.JLayeredPane();
        LogInPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        RegisterCheckbox = new javax.swing.JCheckBox();
        LoggedInPanel = new javax.swing.JPanel();
        LoggedInLabel = new javax.swing.JLabel();
        CurrentDirectoryField = new javax.swing.JTextField();
        BrowseButton = new javax.swing.JButton();
        CurrentDirectoryLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LogOutButton = new javax.swing.JButton();
        DoneLabel = new javax.swing.JLabel();

        LoginLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(LoginLabel, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.LoginLabel.text")); // NOI18N

        UsernameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(UsernameLabel, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.UsernameLabel.text")); // NOI18N

        PasswordLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(PasswordLabel, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.PasswordLabel.text")); // NOI18N

        UsernameField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        UsernameField.setText(org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.UsernameField.text")); // NOI18N

        PasswordField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PasswordField.setText(org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.PasswordField.text")); // NOI18N

        LoginButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(LoginButton, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.LoginButton.text")); // NOI18N
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        RegisterCheckbox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(RegisterCheckbox, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.RegisterCheckbox.text")); // NOI18N
        RegisterCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogInPanelLayout = new javax.swing.GroupLayout(LogInPanel);
        LogInPanel.setLayout(LogInPanelLayout);
        LogInPanelLayout.setHorizontalGroup(
            LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LogInPanelLayout.createSequentialGroup()
                        .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameLabel)
                            .addComponent(PasswordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanelLayout.createSequentialGroup()
                        .addComponent(RegisterCheckbox)
                        .addGap(112, 112, 112)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        LogInPanelLayout.setVerticalGroup(
            LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginLabel)
                .addGap(18, 18, 18)
                .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel))
                .addGap(18, 18, 18)
                .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginButton)
                .addGap(18, 18, 18)
                .addComponent(RegisterCheckbox)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        LoggedInPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LoggedInLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LoggedInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(LoggedInLabel, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.LoggedInLabel.text")); // NOI18N

        CurrentDirectoryField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CurrentDirectoryField.setText(org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.CurrentDirectoryField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(BrowseButton, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.BrowseButton.text")); // NOI18N
        BrowseButton.setToolTipText(org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.BrowseButton.toolTipText")); // NOI18N
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        CurrentDirectoryLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CurrentDirectoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(CurrentDirectoryLabel, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.CurrentDirectoryLabel.text")); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        org.openide.awt.Mnemonics.setLocalizedText(LogOutButton, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.LogOutButton.text")); // NOI18N
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        DoneLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(DoneLabel, org.openide.util.NbBundle.getMessage(BittlePanel.class, "BittlePanel.DoneLabel.text")); // NOI18N

        javax.swing.GroupLayout LoggedInPanelLayout = new javax.swing.GroupLayout(LoggedInPanel);
        LoggedInPanel.setLayout(LoggedInPanelLayout);
        LoggedInPanelLayout.setHorizontalGroup(
            LoggedInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoggedInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoggedInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoggedInPanelLayout.createSequentialGroup()
                        .addGroup(LoggedInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoggedInPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(LoggedInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CurrentDirectoryField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CurrentDirectoryLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(LoggedInPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(BrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LoggedInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoggedInPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LoggedInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        LoggedInPanelLayout.setVerticalGroup(
            LoggedInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoggedInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoggedInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoggedInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(LoggedInPanelLayout.createSequentialGroup()
                        .addGroup(LoggedInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoggedInPanelLayout.createSequentialGroup()
                                .addComponent(CurrentDirectoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CurrentDirectoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoggedInPanelLayout.createSequentialGroup()
                                .addComponent(DoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LogOutButton)))
                        .addGap(30, 30, 30)
                        .addComponent(BrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );

        OptionsLayeredPane.setLayer(LogInPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        OptionsLayeredPane.setLayer(LoggedInPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout OptionsLayeredPaneLayout = new javax.swing.GroupLayout(OptionsLayeredPane);
        OptionsLayeredPane.setLayout(OptionsLayeredPaneLayout);
        OptionsLayeredPaneLayout.setHorizontalGroup(
            OptionsLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoggedInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(OptionsLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OptionsLayeredPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LogInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        OptionsLayeredPaneLayout.setVerticalGroup(
            OptionsLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsLayeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoggedInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(OptionsLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OptionsLayeredPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LogInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OptionsLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OptionsLayeredPane)
        );
    }// </editor-fold>//GEN-END:initComponents
  
    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseButtonActionPerformed
        
        // Create a Java file chooser for folders
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        // Show the file chooser
        int choice = fileChooser.showOpenDialog(null);
        
        // If the user selected a folder
        if(choice == JFileChooser.APPROVE_OPTION){
            
            // Try to create a Bittle folder in it
            try {
                createBittleDirectory(fileChooser.getSelectedFile().toString(), true);
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
            
            store();    // Stores the new rootpath
            load();     // Shows the new rootpath in the text box
        }
    }//GEN-LAST:event_BrowseButtonActionPerformed

    private void RegisterCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCheckboxActionPerformed
        // If the checkbox is selected, show the register prompts
        if(RegisterCheckbox.isSelected()){
            LoginLabel.setText("Sign Up");
            LoginButton.setText("Sign Up");
        }
        // Otherwise show the log in prompts
        else{
            LoginLabel.setText("Log In");
            LoginButton.setText("Log In");
        }
    }//GEN-LAST:event_RegisterCheckboxActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // Do clilent side log in validation
        // If log in was invalid, do nothing
        if(!validLogin())
            return;
        
        connection.connect(serverName);
        // Update the username and password with the input
        username = UsernameField.getText();
        password = PasswordField.getText();
        
        // If the user wants to register, do that
        if(RegisterCheckbox.isSelected()){
            connection.register(username, password);
            
            // Wait for response from the server
            while(Connection.response == null)
                try {
                    TimeUnit.MILLISECONDS.sleep(50);
                } catch (InterruptedException ex) {
                }
            
            if(connection.checkResponse("register")){
                NotifyDescriptor nd = new NotifyDescriptor.Message("Thanks for signing up, " + username, NotifyDescriptor.INFORMATION_MESSAGE);
                DialogDisplayer.getDefault().notify(nd);
                connection.login(username, password);
            }
            else
                return;
        }
        // Otherwise do the log in stuff
        else{
            connection.login(username, password);
            
            // Wait for response from the server
            while(Connection.response == null)
                try {
                    TimeUnit.MILLISECONDS.sleep(50);
                } catch (InterruptedException ex) {
            }
            
            if(connection.checkResponse("login")){
                NotifyDescriptor nd = new NotifyDescriptor.Message("Welcome Back, " + username, NotifyDescriptor.INFORMATION_MESSAGE);
                DialogDisplayer.getDefault().notify(nd);
            }
            else
                return;
        }
        
        // Set the log in flag to true
        loggedIn = true;
        
        // Try to create the bittle directory
        // If it already exists, rootpath will be updated
        // NOTE: We need to find a way to store each user's preference for this
        // - As it is now, the bittle folder is created in user's home folder
        // - They have to reset it to thier desired path each time
        // - Perhaps we could store their desired path in the server
        // - We would use that instead of "rootpath" for the create call
        try {
            createBittleDirectory(rootpath, false);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        
        store();    // Store the new information
        
        // Show the appropriate screens and text 
        load();
        LogInPanel.setVisible(false);
        LoggedInLabel.setText("Hey There, " + username);
        LoggedInPanel.setVisible(true);
        fileTree.updateTree();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO: add proper logout code here
        logout();
        
        // Update the login screen and file tree
        LoggedInPanel.setVisible(false);
        LogInPanel.setVisible(true);
        fileTree.updateTree();
    }//GEN-LAST:event_LogOutButtonActionPerformed

    void logout(){
        connection.logout();
        loggedIn = false;
        username = "";
        password = "";
        store();
    }
    
    void load() {
        UsernameField.setText(NbPreferences.forModule(BittlePanel.class).get("username", ""));
        PasswordField.setText(NbPreferences.forModule(BittlePanel.class).get("password", ""));
        CurrentDirectoryField.setText(NbPreferences.forModule(BittlePanel.class).get("rootpath", ""));
    }

    void store() {
        NbPreferences.forModule(BittlePanel.class).put("username", username);
        NbPreferences.forModule(BittlePanel.class).put("password", password);
        NbPreferences.forModule(BittlePanel.class).put("rootpath", rootpath);
        NbPreferences.forModule(BittlePanel.class).putBoolean("status", loggedIn);
        SyncList.bittlePath = rootpath;
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseButton;
    private javax.swing.JTextField CurrentDirectoryField;
    private javax.swing.JLabel CurrentDirectoryLabel;
    private javax.swing.JLabel DoneLabel;
    private javax.swing.JPanel LogInPanel;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JLabel LoggedInLabel;
    private javax.swing.JPanel LoggedInPanel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLayeredPane OptionsLayeredPane;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JCheckBox RegisterCheckbox;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * Checks that the user's input is not blank
     * Should probably do more than just check that
     * @return false if the user's input was blank, true otherwise
     */
    private boolean validLogin() {
        if("".equals(PasswordField.getText()) || "".equals(UsernameField.getText())){
            NotifyDescriptor nd = new NotifyDescriptor.Message("Fields cannot be blank!", NotifyDescriptor.ERROR_MESSAGE);
            DialogDisplayer.getDefault().notify(nd);
            return false;
        }
        return true;
    }
    
    /**
     * Creates a new directory for Bittle files
     * @param newPath - the folder where the Bittle directory will be created
     * @param moveFiles - lets the program know the to move the Bittle directory
     */
    private void createBittleDirectory(String newPath, boolean moveFiles) throws IOException{
        
        if(!newPath.substring(newPath.lastIndexOf("\\")).equals("\\Bittle"))
            newPath = newPath + "\\Bittle";
        
        // Create a path for the new folder
        Path newFolder = Paths.get(newPath);
            
        // If the folder does not exist
        if(!Files.exists(newFolder)){
            
            // Attempt to create it
            try {
                Files.createDirectories(newFolder);
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
                }
        }
        
        if(moveFiles && !rootpath.equals(newPath))
                moveDirectories(rootpath, newPath);
        
        rootpath = newPath;
    }
    
    /**
     * Moves the contents of one directory to another
     * @param from - the path of the folder you are moving from
     * @param to - the path of the folder you are moving to
     * @throws IOException 
     */
    private void moveDirectories(String from, String to) throws IOException{
    
        // Get the path of the previous folder 
        Path oldBittleFolder = Paths.get(from);
        
        // Get the path of the new folder
        Path newBittleFolder = Paths.get(to);
            
        // Visit all the files in the Bittle Folder
        Files.walkFileTree(oldBittleFolder, new SimpleFileVisitor<Path>()
        {
            // When a file is encountered, move it to the new path
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException
            {
                Files.move(file, newBittleFolder.resolve(oldBittleFolder.relativize(file)), ATOMIC_MOVE);
                return FileVisitResult.CONTINUE;
            }
        });
        
        // Delete the old bittle folder
        Files.delete(oldBittleFolder);
    }
}